version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    volumes:
      - .:/app